version: "3"
services: 
    redis:
        image: redis
        container_name: scraper-redis
    functions-vietstock:
        build: .
        container_name: functions-vietstock
        command: wait-for-it -s torproxy:8118 -s scraper-redis:6379 -t 600  -- bash
        stdin_open: true
        tty: true
        environment: 
            - REDIS_HOST=scraper-redis
            - USER_COOKIE=
        depends_on: 
            - redis
        volumes:
            - ./functions_vietstock/logs:/opt/functions_vietstock/logs
            - ./functions_vietstock/localData:/opt/functions_vietstock/localData
