version: "3"
services: 
    redis:
        image: redis:6.2
        container_name: scraper-redis
    functions-vietstock:
        build: .
        container_name: functions-vietstock
        command: wait-for-it -s scraper-redis:6379 -t 600  -- bash
        stdin_open: true
        tty: true
        environment: 
            - REDIS_HOST=scraper-redis
            - USER_COOKIE=5BE963FA132986FA87CB2C3CD89BF56995D73DCAC447366B9BA05FB9086299D47E9783E0BC24BCFB3D6852270470A13A0D43C4D62E2EA5FB75EF2BA2C89561178C7A6B4F5FCBB4E9A22EEDFC828634B5BAAD53A3759C93CC0692BA9890DA92C028391758774C805C0F98E2387C4E55A6
        depends_on: 
            - redis
        volumes:
            - ./functions_vietstock/logs:/opt/functions_vietstock/logs
            - ./functions_vietstock/localData:/opt/functions_vietstock/localData
